include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = proto
proto_OBJC_FILES = proto.m listen.m
proto_OBJCFLAGS = -I/usr/local/include/lua52
proto_LDFLAGS = -llua-5.2

include $(GNUSTEP_MAKEFILES)/tool.make
