proto3.out: proto3.m
	gcc -g -std=c99 -o proto3.out proto3.m -pthread -lobjc

proto2.out: proto2.m
	gcc -o proto2.out proto2.m -pthread -lobjc

proto1.out: proto1.c
	gcc -o proto1.out proto1.c -pthread
