include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME = proto6
proto6_OBJC_FILES = proto6.m ./lib/WSFrame.m
#proto6_C_FILES = tcp_io.c http_header.c
proto6_LDFLAGS = -lssl

include $(GNUSTEP_MAKEFILES)/tool.make
